package dev.cocoar.signalarrr.ksp

import com.google.devtools.ksp.isAbstract
import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSAnnotation
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.google.devtools.ksp.symbol.KSPropertyDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.google.devtools.ksp.symbol.Modifier
import com.google.devtools.ksp.validate
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LambdaTypeName
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.ParameterizedTypeName
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.TypeVariableName
import com.squareup.kotlinpoet.WildcardTypeName
import com.squareup.kotlinpoet.ksp.TypeParameterResolver
import com.squareup.kotlinpoet.ksp.toClassName
import com.squareup.kotlinpoet.ksp.toTypeName
import com.squareup.kotlinpoet.ksp.toTypeParameterResolver
import com.squareup.kotlinpoet.ksp.toTypeVariableName
import com.squareup.kotlinpoet.ksp.writeTo

/** Creates the [HubProxyProcessor]; registered through `META-INF/services`. */
public class HubProxyProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        HubProxyProcessor(environment.codeGenerator, environment.logger)
}

/**
 * Generates a `<Interface>Proxy` class for every interface annotated with
 * `@dev.cocoar.signalarrr.HubProxy`, routing each member to `HARRRConnection.send`,
 * `HARRRConnection.invoke` or `HARRRConnection.stream`.
 */
public class HubProxyProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver.getSymbolsWithAnnotation(HUB_PROXY).toList()
        val deferred = mutableListOf<KSAnnotated>()

        for (symbol in symbols) {
            if (!symbol.validate()) {
                deferred += symbol
                continue
            }
            if (symbol !is KSClassDeclaration || symbol.classKind != ClassKind.INTERFACE) {
                logger.error("@HubProxy can only be applied to an interface", symbol)
                continue
            }
            runCatching { generate(symbol) }
                .onFailure { logger.error("Failed to generate a proxy: ${it.message}", symbol) }
        }
        return deferred
    }

    // ------------------------------------------------------------------ generation

    private fun generate(declaration: KSClassDeclaration) {
        val containingFile = declaration.containingFile ?: return
        val annotation = declaration.annotation(HUB_PROXY) ?: return
        val interfaceName = declaration.toClassName()
        val simpleName = declaration.simpleName.asString()
        val kind = annotation.enumEntry("kind") ?: "INTERFACE"
        val prefix = if (kind == "HUB") "" else (annotation.string("name") ?: "").ifEmpty { simpleName }
        val pascalCase = annotation.boolean("pascalCase") ?: true
        val separator = when (kind) {
            "SERVER_METHODS" -> "."
            "HUB" -> ""
            else -> "|"
        }

        val proxyName = "${simpleName}Proxy"
        val proxyClass = ClassName(interfaceName.packageName, proxyName)
        val classResolver = declaration.typeParameters.toTypeParameterResolver()

        val type = TypeSpec.classBuilder(proxyName)
            .addModifiers(KModifier.PUBLIC)
            .addKdoc(
                "Typed proxy of [%T], generated by `dev.cocoar:signalarrr-ksp`. Do not edit.",
                interfaceName,
            )
            .addSuperinterface(interfaceName)
            .primaryConstructor(
                FunSpec.constructorBuilder()
                    .addParameter("connection", HARRR_CONNECTION)
                    .build(),
            )
            .addProperty(
                PropertySpec.builder("connection", HARRR_CONNECTION, KModifier.PRIVATE)
                    .initializer("connection")
                    .build(),
            )
            .addType(companion(proxyClass, prefix))

        for (property in abstractProperties(declaration)) {
            logger.error(
                "@HubProxy cannot implement the property '${property.simpleName.asString()}': a hub member must be " +
                    "a suspend function (send/invoke) or a non-suspend function returning kotlinx.coroutines.flow.Flow<T> (stream).",
                property,
            )
        }

        for (function in abstractFunctions(declaration)) {
            val spec = override(function, prefix + separator, pascalCase, classResolver) ?: continue
            type.addFunction(spec)
        }

        FileSpec.builder(interfaceName.packageName, proxyName)
            .addAnnotation(
                AnnotationSpec.builder(Suppress::class)
                    .addMember("%S, %S", "RedundantVisibilityModifier", "unused")
                    .build(),
            )
            .addType(type.build())
            .build()
            .writeTo(codeGenerator, aggregating = false, originatingKSFiles = listOf(containingFile))
    }

    private fun companion(proxyClass: ClassName, prefix: String): TypeSpec =
        TypeSpec.companionObjectBuilder()
            .addSuperinterface(HUB_PROXY_FACTORY.parameterizedBy(proxyClass))
            .addProperty(
                PropertySpec.builder("PREFIX", STRING, KModifier.PUBLIC, KModifier.CONST)
                    .addKdoc("The interface half of the wire name of every member of this proxy.")
                    .initializer("%S", prefix)
                    .build(),
            )
            .addFunction(
                FunSpec.builder("create")
                    .addModifiers(KModifier.PUBLIC, KModifier.OVERRIDE)
                    .addParameter("connection", HARRR_CONNECTION)
                    .returns(proxyClass)
                    .addStatement("return %T(connection)", proxyClass)
                    .build(),
            )
            .build()

    /**
     * Builds the override of one contract member, or reports an error and returns `null` when the
     * signature has no wire equivalent.
     */
    private fun override(
        function: KSFunctionDeclaration,
        prefix: String,
        pascalCase: Boolean,
        classResolver: TypeParameterResolver,
    ): FunSpec? {
        val name = function.simpleName.asString()
        val resolver = function.typeParameters.toTypeParameterResolver(classResolver)
        val genericArguments = function.annotation(GENERIC_ARGUMENTS)?.strings("typeNames")

        if (function.typeParameters.isNotEmpty() && genericArguments == null) {
            logger.error(
                "'$name' declares type parameters; annotate it with @GenericArguments(\"...\") naming the .NET " +
                    "type arguments to send, or drop the type parameters.",
                function,
            )
            return null
        }

        val isSuspend = Modifier.SUSPEND in function.modifiers
        val returnType: KSType? = function.returnType?.resolve()
        val wireName = prefix + (
            function.annotation(HUB_METHOD)?.string("name")
                ?: if (pascalCase) name.replaceFirstChar { it.uppercaseChar() } else name
            )

        val builder = FunSpec.builder(name).addModifiers(KModifier.OVERRIDE)
        if (isSuspend) builder.addModifiers(KModifier.SUSPEND)
        builder.addTypeVariables(function.typeParameters.map { it.toTypeVariableName(classResolver) as TypeVariableName })

        val parameters = function.parameters.mapIndexed { index, parameter ->
            val parameterName = parameter.name?.asString() ?: "arg$index"
            parameterName to ParameterSpec.builder(parameterName, parameter.type.toTypeName(resolver)).build()
        }
        parameters.forEach { builder.addParameter(it.second) }
        val arguments = parameters.map { it.first }

        return when {
            isSuspend && (returnType == null || returnType.isUnit()) -> {
                builder.addStatement("%L", call("send", null, wireName, arguments, genericArguments)).build()
            }

            isSuspend -> {
                val type = function.returnType!!.toTypeName(resolver)
                if (!reifiable(type, function, name)) return null
                builder.returns(type)
                    .addCode("return %L", call("invoke", type, wireName, arguments, genericArguments))
                    .build()
            }

            returnType != null && returnType.isFlow() -> {
                val item = returnType.arguments.firstOrNull()?.type?.toTypeName(resolver)
                if (item == null) {
                    logger.error("'$name' returns a Flow without an item type argument.", function)
                    return null
                }
                if (!reifiable(item, function, name)) return null
                builder.returns(FLOW.parameterizedBy(item))
                    .addCode("return %L", call("stream", item, wireName, arguments, genericArguments))
                    .build()
            }

            else -> {
                logger.error(
                    "'$name' cannot be routed to the connection: a hub member must be a suspend function " +
                        "(returning Unit for a fire-and-forget send, or a value for an invoke) or a non-suspend " +
                        "function returning kotlinx.coroutines.flow.Flow<T> for a stream.",
                    function,
                )
                null
            }
        }
    }

    /**
     * `HARRRConnection.invoke`/`stream` decode through a *reified* type argument, and an override
     * can never be `inline reified`. So a result type built out of the function's own type
     * parameters has no generated form that compiles — report it rather than emit broken code.
     */
    private fun reifiable(type: TypeName, function: KSFunctionDeclaration, name: String): Boolean {
        val variables = function.typeParameters.map { it.name.asString() }.toSet()
        if (variables.isEmpty() || !type.usesTypeVariable(variables)) return true
        logger.error(
            "'$name' produces '$type', which is built from its own type parameters. The connection decodes a " +
                "result through a reified type argument, which an override cannot declare. Give the member a " +
                "concrete result type and name the .NET type arguments with @GenericArguments(\"...\") instead " +
                "(type parameters are fine when they appear only in the parameters of a fire-and-forget send).",
            function,
        )
        return false
    }

    private fun TypeName.usesTypeVariable(names: Set<String>): Boolean = when (this) {
        is TypeVariableName -> name in names || bounds.any { it.usesTypeVariable(names) }
        is ParameterizedTypeName -> typeArguments.any { it.usesTypeVariable(names) }
        is WildcardTypeName -> (inTypes + outTypes).any { it.usesTypeVariable(names) }
        is LambdaTypeName -> receiver?.usesTypeVariable(names) == true ||
            parameters.any { it.type.usesTypeVariable(names) } ||
            returnType.usesTypeVariable(names)
        else -> false
    }

    /** `connection.<method><T>("Wire|Name", a, b, genericArguments = listOf("..."))`. */
    private fun call(
        method: String,
        typeArgument: TypeName?,
        wireName: String,
        arguments: List<String>,
        genericArguments: List<String>?,
    ): CodeBlock {
        val block = CodeBlock.builder().add("connection.%N", method)
        if (typeArgument != null) block.add("<%T>", typeArgument)
        block.add("(%S", wireName)
        arguments.forEach { block.add(", %N", it) }
        if (!genericArguments.isNullOrEmpty()) {
            block.add(", genericArguments·=·%M(", LIST_OF)
            genericArguments.forEachIndexed { index, value ->
                if (index > 0) block.add(", ")
                block.add("%S", value)
            }
            block.add(")")
        }
        block.add(")")
        return block.build()
    }

    // ------------------------------------------------------------------ member discovery

    /** Every abstract function of the interface, inherited ones included, without duplicates. */
    private fun abstractFunctions(declaration: KSClassDeclaration): List<KSFunctionDeclaration> {
        val seen = mutableSetOf<String>()
        return declaration.getAllFunctions()
            .filter { it.isAbstract && it.simpleName.asString() !in OBJECT_MEMBERS }
            .filter { seen.add(it.signatureKey()) }
            .toList()
    }

    private fun abstractProperties(declaration: KSClassDeclaration): List<KSPropertyDeclaration> {
        val seen = mutableSetOf<String>()
        return declaration.getAllProperties()
            .filter { it.isAbstract() }
            .filter { seen.add(it.simpleName.asString()) }
            .toList()
    }

    private fun KSFunctionDeclaration.signatureKey(): String =
        simpleName.asString() + "(" + parameters.joinToString(",") {
            it.type.resolve().declaration.qualifiedName?.asString() ?: it.type.toString()
        } + ")"

    // ------------------------------------------------------------------ helpers

    private fun KSType.isUnit(): Boolean =
        !isMarkedNullable && declaration.qualifiedName?.asString() == "kotlin.Unit"

    private fun KSType.isFlow(): Boolean =
        declaration.qualifiedName?.asString() == "kotlinx.coroutines.flow.Flow"

    private fun KSAnnotated.annotation(qualifiedName: String): KSAnnotation? =
        annotations.firstOrNull {
            it.annotationType.resolve().declaration.qualifiedName?.asString() == qualifiedName
        }

    private fun KSAnnotation.argument(name: String): Any? =
        arguments.firstOrNull { it.name?.asString() == name }?.value
            ?: defaultArguments.firstOrNull { it.name?.asString() == name }?.value

    private fun KSAnnotation.string(name: String): String? = argument(name) as? String

    private fun KSAnnotation.boolean(name: String): Boolean? = argument(name) as? Boolean

    /** The simple name of an enum entry argument, whichever representation the KSP version uses. */
    private fun KSAnnotation.enumEntry(name: String): String? = when (val value = argument(name)) {
        null -> null
        is KSClassDeclaration -> value.simpleName.asString()
        is KSType -> value.declaration.simpleName.asString()
        else -> value.toString().substringAfterLast('.')
    }

    private fun KSAnnotation.strings(name: String): List<String> =
        when (val value = argument(name)) {
            is List<*> -> value.mapNotNull { it as? String }
            is Array<*> -> value.mapNotNull { it as? String }
            is String -> listOf(value)
            else -> emptyList()
        }

    private companion object {
        const val PACKAGE = "dev.cocoar.signalarrr"
        const val HUB_PROXY = "$PACKAGE.HubProxy"
        const val HUB_METHOD = "$PACKAGE.HubMethod"
        const val GENERIC_ARGUMENTS = "$PACKAGE.GenericArguments"

        val HARRR_CONNECTION = ClassName(PACKAGE, "HARRRConnection")
        val HUB_PROXY_FACTORY = ClassName(PACKAGE, "HubProxyFactory")
        val FLOW = ClassName("kotlinx.coroutines.flow", "Flow")
        val LIST_OF = com.squareup.kotlinpoet.MemberName("kotlin.collections", "listOf")

        val OBJECT_MEMBERS = setOf("equals", "hashCode", "toString", "<init>")
    }
}
