using System.Linq;
using System.Text;
using Cocoar.SignalARRR.SourceGenerator.Model;

namespace Cocoar.SignalARRR.SourceGenerator.Emitters;

internal static class ProxyEmitter
{
    public static string Emit(ContractInterfaceInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Channels;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Cocoar.SignalARRR.ProxyGenerator;");
        sb.AppendLine();
        sb.AppendLine($"namespace {info.Namespace}.SignalARRR;");
        sb.AppendLine();
        sb.AppendLine($"[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine($"internal partial class {info.ProxyClassName} : global::{info.FullName}");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly ProxyCreatorHelper _helper;");
        sb.AppendLine($"    private const string Prefix = \"{info.FullName}\";");
        sb.AppendLine();
        sb.AppendLine($"    public {info.ProxyClassName}(ProxyCreatorHelper helper) => _helper = helper;");

        foreach (var method in info.Methods)
        {
            sb.AppendLine();
            EmitMethod(sb, method);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitMethod(StringBuilder sb, ContractMethodInfo method)
    {
        var typeParams = method.TypeParameterNames.Length > 0
            ? "<" + string.Join(", ", method.TypeParameterNames) + ">"
            : "";

        var parameters = string.Join(", ", method.Parameters.Select(FormatParameter));
        var signature = $"    public {method.ReturnTypeFullName} {method.Name}{typeParams}({parameters})";
        sb.AppendLine(signature);

        // Build args array (excluding CancellationToken)
        var nonCtParams = method.Parameters.Where(p => !p.IsCancellationToken).ToList();
        var argsExpr = nonCtParams.Count == 0
            ? "Array.Empty<object>()"
            : "new object[] { " + string.Join(", ", nonCtParams.Select(p => p.Name + "!")) + " }";

        // CancellationToken: use the last one, or default
        var ctParam = method.Parameters.Where(p => p.IsCancellationToken).LastOrDefault();
        var ctExpr = ctParam.IsCancellationToken ? ctParam.Name : "default";

        // Generic arguments
        var genericArgsExpr = method.TypeParameterNames.Length > 0
            ? "new string[] { " + string.Join(", ", method.TypeParameterNames.Select(tp => $"typeof({tp}).FullName!")) + " }"
            : "Array.Empty<string>()";

        var methodNameExpr = $"Prefix + \"|{method.Name}\"";

        switch (method.ReturnCategory)
        {
            case ReturnTypeCategory.Void:
                sb.AppendLine($"        => _helper.Send({methodNameExpr}, {argsExpr}, {genericArgsExpr}, {ctExpr});");
                break;

            case ReturnTypeCategory.Task:
                sb.AppendLine($"        => _helper.SendAsync({methodNameExpr}, {argsExpr}, {genericArgsExpr}, {ctExpr});");
                break;

            case ReturnTypeCategory.TaskOfT:
                sb.AppendLine($"        => _helper.InvokeAsync<{method.ElementTypeFullName}>({methodNameExpr}, {argsExpr}, {genericArgsExpr}, {ctExpr});");
                break;

            case ReturnTypeCategory.SyncReturn:
                sb.AppendLine($"        => _helper.Invoke<{method.ReturnTypeFullName}>({methodNameExpr}, {argsExpr}, {genericArgsExpr}, {ctExpr});");
                break;

            case ReturnTypeCategory.ChannelReader:
                sb.AppendLine($"        => _helper.ToChannelReader(");
                sb.AppendLine($"            _helper.StreamAsync<{method.ElementTypeFullName}>({methodNameExpr}, {argsExpr}, {genericArgsExpr}, {ctExpr}), {ctExpr});");
                break;

            case ReturnTypeCategory.Observable:
                sb.AppendLine($"        => _helper.ToObservable(");
                sb.AppendLine($"            _helper.StreamAsync<{method.ElementTypeFullName}>({methodNameExpr}, {argsExpr}, {genericArgsExpr}, {ctExpr}));");
                break;

            case ReturnTypeCategory.AsyncEnumerable:
                sb.AppendLine($"        => _helper.StreamAsync<{method.ElementTypeFullName}>({methodNameExpr}, {argsExpr}, {genericArgsExpr}, {ctExpr});");
                break;
        }
    }

    private static string FormatParameter(ContractParameterInfo param)
    {
        var result = $"{param.TypeFullName} {param.Name}";
        if (param.HasDefaultValue)
            result += $" = {param.DefaultValueLiteral}";
        return result;
    }
}
