<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;netstandard2.0</TargetFrameworks>
    <AssemblyName>Cocoar.SignalARRR.Client</AssemblyName>
    <RootNamespace>Cocoar.SignalARRR.Client</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Bernhard Windisch</Authors>
    <Company>-</Company>
    <Description></Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/windischb/SignalARRR</PackageProjectUrl>
    <RepositoryUrl>https://github.com/windischb/SignalARRR</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageId>Cocoar.SignalARRR.Client</PackageId>
    <Product>Cocoar.SignalARRR.Client</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cocoar.Reflectensions" />
    <PackageReference Include="Cocoar.Reflectensions.Invoke" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="System.Interactive.Async" />
    <PackageReference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cocoar.SignalARRR.ProxyGenerator\Cocoar.SignalARRR.ProxyGenerator.csproj" />
    <ProjectReference Include="..\Cocoar.SignalARRR.Common\Cocoar.SignalARRR.Common.csproj" />
  </ItemGroup>

</Project>
