<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Cocoar.SignalARRR.Server</AssemblyName>
    <RootNamespace>Cocoar.SignalARRR.Server</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Bernhard Windisch</Authors>
    <Company>-</Company>
    <Description></Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/windischb/SignalARRR</PackageProjectUrl>
    <RepositoryUrl>https://github.com/windischb/SignalARRR</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageId>Cocoar.SignalARRR.Server</PackageId>
    <Product>Cocoar.SignalARRR.Server</Product>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Cocoar.Reflectensions" />
    <PackageReference Include="Cocoar.Reflectensions.Invoke" />
    <PackageReference Include="ImpromptuInterface" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" />
    <PackageReference Include="System.Reactive.Linq" />
    <PackageReference Include="System.Interactive.Async" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\Cocoar.SignalARRR.Common\Cocoar.SignalARRR.Common.csproj" />
    <ProjectReference Include="..\Cocoar.SignalARRR.ProxyGenerator\Cocoar.SignalARRR.ProxyGenerator.csproj" />
  </ItemGroup>

</Project>
