<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Cocoar.SignalARRR.ProxyGenerator</AssemblyName>
    <RootNamespace>Cocoar.SignalARRR.ProxyGenerator</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Bernhard Windisch</Authors>
    <Company>-</Company>
    <Description></Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/windischb/SignalARRR</PackageProjectUrl>
    <RepositoryUrl>https://github.com/windischb/SignalARRR</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageId>Cocoar.SignalARRR.ProxyGenerator</PackageId>
    <Product>Cocoar.SignalARRR.ProxyGenerator</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Reactive.Linq" />
  </ItemGroup>


</Project>
